Update How to create Terminal User Interfaces (TUI)

diff --git a/Terminal User Interfaces/How to create Terminal User Interfaces (TUI) b/Terminal User Interfaces/How to create Terminal User Interfaces (TUI)
--- a/Terminal User Interfaces/How to create Terminal User Interfaces (TUI)
+++ b/Terminal User Interfaces/How to create Terminal User Interfaces (TUI)
@@ -1,1 +1,206 @@
+apt install dialog
+
+
+просто окошо с названием
+dialog --title "Demo" --msgbox "Hello Deisling! Hello Deisling! Hello Deisling! " 0 0
+
+выбор да или нет 
+dialog --title "Demo"  --yesno "Please select yes or no" 0 0
+
+
+обозначения 
+yes - code 0
+no - code 1
+
+
+что будет если нажать на да или нет 
+dialog --yesno "Please select yes or no" 0 0 && dialog --msgbox "The answer was yes" 0 0 || dialog --msgbox "The answer was no" 0 0
+
+
+сделать переменную, но без звездочен для пароля
+VAR=$(dialog --inputbox "Please enter your password:" 0 0 3>&1 1>&2 2>&3 3>&-)
+
+переменную можно проверить потом следующим образом
+echo $VAR
+
+сделать переменную, но не видно сколько символов вводишь
+VAR=$(dialog --passwordbox "Please enter your password:" 0 0 3>&1 1>&2 2>&3 3>&-)
+
+сделать переменную и видно сколько символов вводишь звездочками 
+VAR=$(dialog --insecure --passwordbox "Please enter your password:" 0 0 3>&1 1>&2 2>&3 3>&-)
+
+
+
+
+сам скрипт 
+#!/bin/bash
+
+PASS=$(dialog --title "Multi-Factor Authentication" \
+        --clear \
+        --insecure \
+        --passwordbox "Please enter your MFA code:" 0 0 3>&1 1>&2 2>&3 3>&-); clear
+USER_SECRET=$(sed -n -1p $HOME/.google_authenticator)
+TOTP=$(oathtool --topt -b $USER_SECRET)
+[[ "$PASS" -ne "$TOTP" ]] && { dialog --title "Error" --msgbox "Incorrect code!" 5 25; clear; exit 1; }
+SER=$(dialog --menu "Select server:" 0 0 0 \
+        1 "Ununtu Deisling"     \
+        2 "Fedora Deisling"     \
+        3>&1 1>&2 2>&3 3>&-); clear
+case $SER in
+        1) ssh serhio@192.168.146.128 ; exit ;;
+        2) ssh fedora@192.168.146.129 ; exit ;;
+
+
+
+
+
+открыть папку 
+chown -R jump:jump /home/jump/.scripts/
+перезагрузить службу 
+systemctl restart ssh
+
+
+
+поменять ssh конфиг на
+
+
+# This is the sshd server system-wide configuration file.  See
+# sshd_config(5) for more information.
+
+# This sshd was compiled with PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
+
+# The strategy used for options in the default sshd_config shipped with
+# OpenSSH is to specify options with their default value where
+# possible, but leave them commented.  Uncommented options override the
+# default value.
+
+Include /etc/ssh/sshd_config.d/*.conf
+
+#Port 22
+#AddressFamily any
+#ListenAddress 0.0.0.0
+#ListenAddress ::
+
+#HostKey /etc/ssh/ssh_host_rsa_key
+#HostKey /etc/ssh/ssh_host_ecdsa_key
+#HostKey /etc/ssh/ssh_host_ed25519_key
+
+# Ciphers and keying
+#RekeyLimit default none
+
+# Logging
+#SyslogFacility AUTH
+#LogLevel INFO
+
+# Authentication:
+
+#LoginGraceTime 2m
+
+# Disable root ssh access
+PermitRootLogin no
+#StrictModes yes
+#MaxAuthTries 6
+#MaxSessions 10
+
+#PubkeyAuthentication yes
+
+# Expect .ssh/authorized_keys2 to be disregarded by default in future.
+#AuthorizedKeysFile     .ssh/authorized_keys .ssh/authorized_keys2
+
+#AuthorizedPrincipalsFile none
+
+#AuthorizedKeysCommand none
+#AuthorizedKeysCommandUser nobody
+
+# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
+#HostbasedAuthentication no
+# Change to yes if you don't trust ~/.ssh/known_hosts for
+# HostbasedAuthentication
+#IgnoreUserKnownHosts no
+# Don't read the user's ~/.rhosts and ~/.shosts files
+#IgnoreRhosts yes
+
+# To disable tunneled clear text passwords, change to no here!
+PasswordAuthentication yes
+#PermitEmptyPasswords no
+
+# Change to yes to enable challenge-response passwords (beware issues with
+# some PAM modules and threads)
+ChallengeResponseAuthentication yes
+
+# Kerberos options
+#KerberosAuthentication no
+#KerberosOrLocalPasswd yes
+#KerberosTicketCleanup yes
+#KerberosGetAFSToken no
+
+# GSSAPI options
+#GSSAPIAuthentication no
+#GSSAPICleanupCredentials yes
+#GSSAPIStrictAcceptorCheck yes
+#GSSAPIKeyExchange no
+
+# Set this to 'yes' to enable PAM authentication, account processing,
+# and session processing. If this is enabled, PAM authentication will
+# be allowed through the KbdInteractiveAuthentication and
+# PasswordAuthentication.  Depending on your PAM configuration,
+# PAM authentication via KbdInteractiveAuthentication may bypass
+# the setting of "PermitRootLogin without-password".
+# If you just want the PAM account and session checks to run without
+# PAM authentication, then enable this but set PasswordAuthentication
+# and KbdInteractiveAuthentication to 'no'.
+UsePAM yes
+
+#AllowAgentForwarding yes
+#AllowTcpForwarding yes
+#GatewayPorts no
+X11Forwarding yes
+#X11DisplayOffset 10
+#X11UseLocalhost yes
+#PermitTTY yes
+PrintMotd no
+#PrintLastLog yes
+#TCPKeepAlive yes
+#PermitUserEnvironment no
+#Compression delayed
+#ClientAliveInterval 0
+#ClientAliveCountMax 3
+#UseDNS no
+#PidFile /run/sshd.pid
+#MaxStartups 10:30:100
+#PermitTunnel no
+#ChrootDirectory none
+#VersionAddendum none
+
+# no default banner path
+#Banner none
+
+# Allow client to pass locale environment variables
+AcceptEnv LANG LC_*
+
+# override default of no subsystems
+Subsystem       sftp    /usr/lib/openssh/sftp-server
+
+# Example of overriding settings on a per-user basis
+#Match User anoncvs
+#       X11Forwarding no
+#       AllowTcpForwarding no
+#       PermitTTY no
+#       ForceCommand cvs server
+
+
+#AuthenticationMethods publickey,keyboard-interactive password,keyboard-interactive
+Match User jump
+        PermitTTY yes
+        X11Forwarding no
+        PermitTunnel no
+        GatewayPorts no
+        ForceCommand /home/jump/.scripts/menubox
+
+
+
+
+
+
+
 
